collapse_single_pages: true
nav:
  - index.md
  - Cluster_Slow_Rank_Analysis.md
  - Host_Bound_Analysis_with_Linux_Kernel_Trace.md
  - Jupyter_Plugin_Installation_Guide.md
  - Keyboard_Shortcuts.md
  - profiler_memory_example.md
  - pytorch_snapshot_memory_analysis.md
  - Single_Card_Top_Down_Dispatch_Analysis.md
  - Timeline_Common_Lanes_and_Interface.md
  - verl_Memory_Snapshot_Collection_and_Analysis.md
